
webdriver.driver=chrome
webdriver.edge.driver=src/test/resources/driver/chromedriver.exe
web.browser.headless=false
serenity.outputDirectory=target/site/serenity
serenity.reports.show.step.details=true
serenity.reports.show.full.stacktrace=true
serenity.logging=VERBOSE

